name: Daily
on: 
  push:
    branches:
      - main
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: pip install -r requirements.txt
      - run: |
      python main.py \
      --mail.host ${{ secrets.MAIL_HOST }} \
      --mail.username ${{ secrets.MAIL_USERNAME }} \
      --mail.password ${{ secrets.MAIL_PASSWORD }} \
      --mail.to ${{ secrets.MAIL_TO }} 
